name = "gigscale-scan-worker"
main = "src/worker.ts"
compatibility_date = "2026-03-20"
workers_dev = false
preview_urls = false
routes = [
  { pattern = "scanner.gigscale.app", zone_name = "gigscale.app", custom_domain = true }
]

compatibility_flags = [ "nodejs_compat" ]

[[queues.producers]]
queue = "gigscale-scan-jobs"
binding = "gigscale_scan_jobs"

[[queues.consumers]]
queue = "gigscale-scan-jobs"
max_batch_size = 1
max_batch_timeout = 30
max_retries = 3

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1