import type { Metadata } from "next";
import Link from "next/link";

import { LegalArticle } from "@/components/shared/LegalArticle";
import { siteConfig } from "@/config/site";

export const metadata: Metadata = {
  title: "Disclaimer",
  description: `Disclaimer for ${siteConfig.name}. Important information about AI-generated content and service limitations.`,
};

export default function DisclaimerPage() {
  const lastUpdated = "March 9, 2026";

  return (
    <LegalArticle>
      <h1>Disclaimer</h1>
      <p className="lead">
        Last updated: {lastUpdated}
      </p>

      <p>
        The information and services provided by {siteConfig.name} (the
        &quot;Service&quot;) at {siteConfig.domain} are intended for general
        informational and productivity purposes. By using the Service, you
        acknowledge and agree to the following.
      </p>

      <h2>1. AI-Generated Content</h2>
      <p>
        {siteConfig.name} uses artificial intelligence to analyze freelancer
        profiles, generate scores, provide suggestions, and create content
        rewrites. You acknowledge that:
      </p>
      <ul>
        <li>
          AI-generated outputs are <strong>recommendations only</strong> and
          should not be treated as professional advice.
        </li>
        <li>
          Profile scores are generated by our AI models and{" "}
          <strong>do not guarantee</strong> any specific outcome, ranking, or
          performance on third-party freelancing platforms.
        </li>
        <li>
          AI-generated suggestions and rewrites may contain inaccuracies,
          generalizations, or content that does not fully represent your skills
          and experience.
        </li>
        <li>
          You are solely responsible for reviewing, editing, and approving any
          AI-generated content before using it on your profiles.
        </li>
      </ul>

      <h2>2. No Guarantee of Results</h2>
      <p>
        While {siteConfig.name} is designed to help optimize freelancer
        profiles, we make no guarantees regarding:
      </p>
      <ul>
        <li>
          Increased visibility, ranking, or placement on any freelancing
          platform (Upwork, Fiverr, or others).
        </li>
        <li>
          Increased client inquiries, project invitations, or earnings.
        </li>
        <li>
          The accuracy or completeness of profile analyses or scores.
        </li>
        <li>
          Compatibility of suggested changes with any specific platform&apos;s
          terms of service or guidelines.
        </li>
      </ul>

      <h2>3. Third-Party Platforms</h2>
      <p>
        {siteConfig.name} is not affiliated with, endorsed by, or partnered
        with any freelancing platform including Upwork, Fiverr, Freelancer.com,
        Toptal, or any other similar service. The use of these platform names is
        for reference purposes only.
      </p>
      <p>
        You are responsible for ensuring that any changes you make to your
        profiles comply with the respective platform&apos;s terms of service
        and community guidelines.
      </p>

      <h2>4. Professional Advice</h2>
      <p>
        The Service does not constitute professional career counseling, legal
        advice, or business consulting. For specific professional guidance,
        please consult qualified professionals in the relevant field.
      </p>

      <h2>5. Service Availability</h2>
      <p>
        We strive to maintain high availability, but the Service may be subject
        to interruptions, maintenance windows, or downtime. We do not guarantee
        uninterrupted or error-free operation.
      </p>

      <h2>6. Data Accuracy</h2>
      <p>
        While we take reasonable measures to ensure the accuracy of our
        analyses, AI models are inherently imperfect. Scores, suggestions, and
        rewrites are based on general optimization principles and may not
        account for niche-specific factors, regional differences, or recent
        platform algorithm changes.
      </p>

      <h2>7. Limitation of Liability</h2>
      <p>
        To the fullest extent permitted by law, {siteConfig.name} and its
        operators shall not be held liable for any damages, losses, or
        consequences arising from the use of AI-generated content, profile
        modifications based on our suggestions, or any actions taken in
        reliance on the Service.
      </p>

      <h2>8. Changes to This Disclaimer</h2>
      <p>
        We reserve the right to update this Disclaimer at any time. Changes will
        be posted on this page with an updated &quot;Last updated&quot; date.
      </p>

      <h2>9. Contact Us</h2>
      <p>
        If you have questions about this Disclaimer, contact us at{" "}
        <a href={`mailto:${siteConfig.supportEmail}`}>
          {siteConfig.supportEmail}
        </a>
        .
      </p>

      <hr />

      <p className="text-sm text-muted-foreground">
        See also: <Link href="/terms">Terms of Service</Link> &middot;{" "}
        <Link href="/privacy">Privacy Policy</Link> &middot;{" "}
        <Link href="/refund-policy">Refund Policy</Link> &middot;{" "}
        <Link href="/billing-policy">Billing &amp; Credits Policy</Link>
      </p>
    </LegalArticle>
  );
}
